[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "Hr83GxtFmw1Af1QiCkCi4e1wmQ2R8V7cSHTrxZJuiYV7"
betting_dapp = "7t3Ao9DeLrYUrduk2Xa3EAF39NAYhSWGEqxPY98ShmUf"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./betting-dapp_keypair.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
