[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "7t3Ao9DeLrYUrduk2Xa3EAF39NAYhSWGEqxPY98ShmUf"
betting_dapp = "7t3Ao9DeLrYUrduk2Xa3EAF39NAYhSWGEqxPY98ShmUf"

[programs.devnet]
counter = "7t3Ao9DeLrYUrduk2Xa3EAF39NAYhSWGEqxPY98ShmUf"
betting_dapp = "7t3Ao9DeLrYUrduk2Xa3EAF39NAYhSWGEqxPY98ShmUf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sam/.config/solana/id.json"

[scripts]
init-program-state = "../node_modules/.bin/nx run anchor:jest ./tests/init-program-state.spec.ts"
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
