[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "7t3Ao9DeLrYUrduk2Xa3EAF39NAYhSWGEqxPY98ShmUf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"
init-program-state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-program-state.ts"
read-program-state = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/read-program-state.ts"
init-spl-bet-a = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-place-spl-bet-a.ts"
init-spl-bet-b = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-place-spl-bet-b.ts"
init-sol-bet-a = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-place-sol-bet-a.ts"
init-sol-bet-b = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init-place-sol-bet-b.ts"
place-spl-bet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/place-spl-bet.ts"
place-sol-bet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/place-sol-bet.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
